yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),

]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace = 'posts')),
    path('admin/', admin.site.urls),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    """Описывает поля модели Group и их типы."""

    title = models.CharField(max_length=200)
    slug = models.SlugField()
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    """Класс описывает поля модели Post и их типы."""

    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='posts')
    group = models.ForeignKey(Group, on_delete=models.SET_NULL,
                              blank=True, null=True)
# Create your models here.

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Group


# Create your views here.
# Главная страница
def index(request):
    """View - функция для главной страницы проекта."""

    posts = Post.objects.order_by('-pub_date')[:10]
    title_index = 'Последние обновления на сайте'
    context = {
        'posts': posts,
        'title_index': title_index,
    }
    return render(request, 'posts/index.html', context)


# Страница со списком постов
def group_posts(request, slug):
    """View - функция для страницы с постами, отфильтрованными по группам."""

    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    title_group = 'Записи сообщества'
    context = {
        'group': group,
        'posts': posts,
        'title_group': title_group,

    }
    return render(request, 'posts/group_list.html', context)

yatube/templates/base.html
{% load static %}
<!-- templates/base.html -->
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->         
  <head>  
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.сss' %}">
  </head>
  <body>       
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      <div class="container">
      {% block content %}
        Контент не подвезли :(
      {% endblock %}
      </div>  
    </main>
    <!-- Использованы классы бустрапа: -->
    <!-- border-top: создаёт тонкую линию сверху блока -->
    <!-- text-center: выравнивает текстовые блоки внутри блока по центру -->
    <!-- py-3: контент внутри размещается с отсупом сверху и снизу -->         
    <footer class="border-top text-center py-3">
      {% include 'includes/footer.html' %} 
    </footer>
  </body>
</html> 

yatube/templates/includes/footer.html
 <!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
{% load static %}
<p>© 2020 Copyright <span style="color:red">Ya</span>tube</p>    

yatube/templates/includes/header.html
{% load static %}
 <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
 <!-- В дальнейшем тут будет создано полноценное меню -->
    <nav class="navbar navbar-light" style="background-color: lightskyblue">
      <div class="container">
         <!-- ссылка должна вести на главную страницу -->
        <a class="navbar-brand" href="{% url 'posts:index' %}">
         <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
         <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
         <span style="color:red">Ya</span>tube
        </a>
      </div>
    </nav>      

yatube/templates/posts/group_list.html
<!-- templates/posts/group_list.html -->
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html> 
{% block content %}
  <head>
    <title>{{ title_group }} {{ group }}</title>
  </head>
  <h1>{{ group }}</h1> 
  <p>{{ group.description }}</p>
  {% for post in posts %}
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
      <p>{{ post.text }}</p>
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %} 
{% endblock %}

yatube/templates/posts/index.html
<!-- templates/posts/index.html -->
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html> 
{% block content %}
  <head>
    <title>{{ title_post }}</title>
  </head>    
  <h1>Последние обновления на сайте</h1>   
  {% for post in posts %}
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
      </li>
      <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
      <p>{{ post.text }}</p>    
  {% if post.group.slug == None %}
    Данный пост не принадлежит ни к одной из групп сайта.
  {% else %}
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
  {% endif %}
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %} 
{% endblock %}